### ISSUE TITLE
error using 10 cells

### ISSUE THREAD

**Issue by shilpagarg** [daewoooo/StrandPhaseR#1]
Working on chromosome 7
 Loading data for 13 WCregions 62.58s
  Sorting matrices: iteration 1 15.4s
  Sorting matrices: iteration 2 15.89s
 Assembling haplotypes 12.72s
 Filling gaps in haplotypesError in BamFile(file, character(0)) : 
  'file' must be character(1) and not NA
Calls: strandPhaseR ... <Anonymous> -> lapply -> lapply -> FUN -> open -> BamFile
Execution halted

**Comment by daewoooo** [comment]
check if you used correct path to the merged file for option fillgaps. It
has to be string path to the merged file.

On Jul 14, 2017 12:43 PM, "shilpagarg" <notifications@github.com> wrote:

Working on chromosome 7
Loading data for 13 WCregions 62.58s
Sorting matrices: iteration 1 15.4s
Sorting matrices: iteration 2 15.89s
Assembling haplotypes 12.72s
Filling gaps in haplotypesError in BamFile(file, character(0)) :
'file' must be character(1) and not NA
Calls: strandPhaseR ... -> lapply -> lapply -> FUN -> open -> BamFile
Execution halted

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/daewoooo/StrandPhaseR/issues/1>, or mute the thread

**Comment by shilpagarg** [comment]
Error in bcftools: The sequence "chr2" not defined in the header of StrandSeq VCF files.
